CREATE TABLE [dbo].[DwD1PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](1) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwD1PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[DwP2PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](2) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwP2PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[DwC2PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](2) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwC2PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[DwP3PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](3) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwP3PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[DwC3PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](3) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwC3PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[DwC33PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](3) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwC33PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[DwC36PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](3) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwC36PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[DwP4PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](4) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwP4PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[DwP5PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](5) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwP5PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
