CREATE TABLE [dbo].[DwD1PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](2) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwD1PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[DwF2PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](4) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwF2PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[DwC2PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](4) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwC2PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[DwF3PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](6) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwF3PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[DwC3PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](6) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwC3PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[DwA5PeroidSpan](
	[P] [bigint]  NOT NULL,
	[NumberId] [char](10) NOT NULL,
	[Spans] [int] NOT NULL,
	[LastN] [int] NOT NULL,
 CONSTRAINT [PK_DwA5PeroidSpan] PRIMARY KEY CLUSTERED 
(
	[P] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
